version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public/

  mysql:
    image: mysql:5.7.29
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: passwd
    volumes: 
      - dbdata:/var/lib/mysql

  php:
    build: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    working_dir: /var/www

volumes:
  dbdata:
